sudo: required
# language: generic 
services:
    - docker

before_install:
    - docker build -t ashwinspg/docker-frontend -f Dockerfile.dev . 
script:
    - docker run ashwinspg/docker-frontend npm run test -- --coverage
    # docker run -e CI=true ashwinspg/docker-frontend npm run test -- --coverage